services:
  dolt:
    image: dolthub/dolt-sql-server:latest
    container_name: zetteln-dolt
    restart: unless-stopped
    volumes:
      - dolt-data:/var/lib/dolt
      - dolt-socket:/var/run/mysqld
    environment:
      DOLT_ROOT_PATH: /var/lib/dolt
    command: ["--socket=/var/run/mysqld/mysqld.sock", "--data-dir=/var/lib/dolt"]
    networks:
      - zetteln-network
    healthcheck:
      test: ["CMD-SHELL", "dolt sql -q 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  client:
    image: imbrem/zetteln-client-data:main
    container_name: zetteln-client
    restart: "no"
    # Populate the named volume /srv/www with the static files from the image
    # This is a one-shot container: it copies files and exits successfully.
    # docker compose up -d will recreate it when the image changes, triggering the copy.
    volumes:
      - client-build:/srv/www
    networks:
      - zetteln-network

  caddy:
    image: caddy:2-alpine
    container_name: zetteln-caddy
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT:-80}:80"
      - "${HOST_HTTPS_PORT:-443}:443"
      - "${HOST_HTTPS_PORT:-443}:443/udp"  # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - client-build:/srv/www:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      DOMAIN: ${DOMAIN:-:80}
    networks:
      - zetteln-network
    depends_on:
      client:
        condition: service_completed_successfully
      api:
        condition: service_started

  api:
    image: imbrem/zetteln-api:main
    container_name: zetteln-api
    restart: unless-stopped
    environment:
      RUST_LOG: info
      DATABASE_SOCKET: /var/run/mysqld/mysqld.sock
    volumes:
      - dolt-socket:/var/run/mysqld:ro
    networks:
      - zetteln-network
    expose:
      - "8080"
    depends_on:
      dolt:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  zetteln-network:
    driver: bridge

volumes:
  dolt-data:
  dolt-socket:
  client-build:
  caddy-data:
  caddy-config:
